/* CompisTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. CompisTokenManager.java */
import java.io.*;
import java.util.*;
import java.io.File;

/** Token Manager. */
@SuppressWarnings("unused")public class CompisTokenManager implements CompisConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x10003ff00L) != 0L)
            return 29;
         if ((active0 & 0x8000000L) != 0L)
            return 6;
         if ((active0 & 0x7c0000L) != 0L)
         {
            jjmatchedKind = 23;
            return 44;
         }
         return -1;
      case 1:
         if ((active0 & 0x7c0000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return -1;
         }
         return -1;
      case 2:
         if ((active0 & 0x7c0000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 3:
         if ((active0 & 0x7c0000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 4:
         if ((active0 & 0x7c0000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x740000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x140000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 23;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x2aa00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x22a00L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active0 & 0x22800L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 18:
         if ((active0 & 0x20800L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 19:
         if ((active0 & 0x20800L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 20:
         if ((active0 & 0x20800L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 21:
         if ((active0 & 0x20800L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 27, 6);
      case 36:
         return jjStopAtPos(0, 31);
      case 58:
         return jjStopAtPos(0, 25);
      case 60:
         jjmatchedKind = 32;
         return jjMoveStringLiteralDfa1_0(0x3ff00L);
      case 61:
         return jjStopAtPos(0, 26);
      case 62:
         return jjStopAtPos(0, 34);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x7c0000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 47:
         return jjMoveStringLiteralDfa2_0(active0, 0x2aa00L);
      case 58:
         return jjMoveStringLiteralDfa2_0(active0, 0x7c0000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x14100L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 58:
         return jjMoveStringLiteralDfa3_0(active0, 0x15500L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x202000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x28200L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 58:
         return jjMoveStringLiteralDfa4_0(active0, 0x2aa00L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x11000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x22000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 108:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(4, 19);
         break;
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x15500L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x11400L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(5, 21);
         break;
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x2aa00L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(5, 22);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x22800L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x8100L);
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(6, 18);
         break;
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x11400L);
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(7, 14);
         break;
      case 68:
         return jjMoveStringLiteralDfa8_0(active0, 0x100L);
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x11400L);
      case 116:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(7, 20);
         break;
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x22800L);
      case 121:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(8, 15);
         break;
      case 68:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x11400L);
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x22800L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x100L);
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x22800L);
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x11400L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x200L);
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x22800L);
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0x11400L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000L);
      case 80:
         return jjMoveStringLiteralDfa12_0(active0, 0x400L);
      case 84:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000L);
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0x100L);
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x22800L);
      case 117:
         return jjMoveStringLiteralDfa12_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa13_0(active0, 0x20000L);
      case 80:
         return jjMoveStringLiteralDfa13_0(active0, 0x800L);
      case 84:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000L);
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x100L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000L);
      case 109:
         return jjMoveStringLiteralDfa13_0(active0, 0x200L);
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000L);
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa14_0(active0, 0x200L);
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000L);
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0x10100L);
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x20400L);
      case 114:
         return jjMoveStringLiteralDfa14_0(active0, 0x800L);
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0x10000L);
      case 108:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000L);
      case 110:
         return jjMoveStringLiteralDfa15_0(active0, 0x20200L);
      case 111:
         return jjMoveStringLiteralDfa15_0(active0, 0x800L);
      case 112:
         return jjMoveStringLiteralDfa15_0(active0, 0x400L);
      case 116:
         return jjMoveStringLiteralDfa15_0(active0, 0x2100L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(15, 8);
         break;
      case 99:
         return jjMoveStringLiteralDfa16_0(active0, 0x20000L);
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x1400L);
      case 108:
         return jjMoveStringLiteralDfa16_0(active0, 0x12000L);
      case 112:
         return jjMoveStringLiteralDfa16_0(active0, 0x800L);
      case 116:
         return jjMoveStringLiteralDfa16_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(16, 9);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(16, 12);
         break;
      case 101:
         return jjMoveStringLiteralDfa17_0(active0, 0x2800L);
      case 108:
         return jjMoveStringLiteralDfa17_0(active0, 0x20000L);
      case 114:
         return jjMoveStringLiteralDfa17_0(active0, 0x400L);
      case 117:
         return jjMoveStringLiteralDfa17_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(17, 13);
         break;
      case 114:
         return jjMoveStringLiteralDfa18_0(active0, 0x800L);
      case 115:
         return jjMoveStringLiteralDfa18_0(active0, 0x10000L);
      case 116:
         return jjMoveStringLiteralDfa18_0(active0, 0x400L);
      case 117:
         return jjMoveStringLiteralDfa18_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa19_0(active0, 0x10400L);
      case 115:
         return jjMoveStringLiteralDfa19_0(active0, 0x20000L);
      case 116:
         return jjMoveStringLiteralDfa19_0(active0, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa20_0(active0, 0x400L);
      case 105:
         return jjMoveStringLiteralDfa20_0(active0, 0x20800L);
      case 111:
         return jjMoveStringLiteralDfa20_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
private int jjMoveStringLiteralDfa20_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0);
      return 20;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa21_0(active0, 0x800L);
      case 110:
         return jjMoveStringLiteralDfa21_0(active0, 0x10000L);
      case 111:
         return jjMoveStringLiteralDfa21_0(active0, 0x20000L);
      case 115:
         return jjMoveStringLiteralDfa21_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0);
}
private int jjMoveStringLiteralDfa21_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0);
      return 21;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(21, 10);
         else if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(21, 16);
         break;
      case 110:
         return jjMoveStringLiteralDfa22_0(active0, 0x20000L);
      case 115:
         return jjMoveStringLiteralDfa22_0(active0, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0);
}
private int jjMoveStringLiteralDfa22_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0);
      return 22;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(22, 11);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(22, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(21, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 44;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 44:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  else if ((0x800700000000000L & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 29:
                  if (curChar == 47)
                  {
                     if (kind > 33)
                        kind = 33;
                  }
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 33;
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 24)
                        kind = 24;
                     { jjCheckNAddStates(3, 5); }
                  }
                  else if ((0x800700000000000L & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  else if (curChar == 60)
                     { jjAddStates(6, 8); }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 34)
                     { jjAddStates(9, 10); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if ((0x800700000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 5:
                  if (curChar == 34)
                     { jjAddStates(9, 10); }
                  break;
               case 7:
                  if ((0x800700100000000L & l) != 0L)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 9:
                  if (curChar == 34 && kind > 30)
                     kind = 30;
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(14, 17); }
                  break;
               case 12:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if (curChar == 62 && kind > 35)
                     kind = 35;
                  break;
               case 19:
                  if (curChar == 58)
                     { jjCheckNAddStates(18, 20); }
                  break;
               case 20:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 21:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(22, 23); }
                  break;
               case 22:
                  if ((0x800700000000000L & l) != 0L)
                     { jjCheckNAddStates(21, 23); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(21, 23); }
                  break;
               case 24:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 25:
                  if ((0x800700000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 27:
                  if (curChar == 47 && kind > 36)
                     kind = 36;
                  break;
               case 28:
                  if (curChar == 60)
                     { jjAddStates(6, 8); }
                  break;
               case 30:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if (curChar == 45 && kind > 5)
                     kind = 5;
                  break;
               case 32:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if (curChar == 45)
                     { jjCheckNAdd(35); }
                  break;
               case 35:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(35, 36); }
                  break;
               case 36:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if (curChar == 62 && kind > 7)
                     kind = 7;
                  break;
               case 39:
                  if (curChar == 47 && kind > 33)
                     kind = 33;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  { jjCheckNAddStates(3, 5); }
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  { jjCheckNAdd(43); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 44:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 29)
                        kind = 29;
                     { jjCheckNAdd(41); }
                  }
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 23)
                        kind = 23;
                     { jjCheckNAdd(41); }
                  }
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 14:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if (curChar == 112)
                     { jjCheckNAddTwoStates(18, 19); }
                  break;
               case 18:
                  if (curChar == 115)
                     { jjCheckNAdd(19); }
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjAddStates(21, 23); }
                  break;
               case 25:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjAddStates(24, 26); }
                  break;
               case 35:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjAddStates(27, 28); }
                  break;
               case 40:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 23)
                     kind = 23;
                  { jjCheckNAdd(41); }
                  break;
               case 41:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  { jjCheckNAdd(41); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 44 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   7, 9, 11, 43, 3, 4, 29, 32, 39, 6, 10, 7, 8, 9, 7, 8, 
   9, 11, 20, 22, 23, 22, 23, 24, 25, 26, 27, 35, 36, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, 
"\74\167\72\167\157\162\144\104\157\143\165\155\145\156\164\76", "\74\57\167\72\167\157\162\144\104\157\143\165\155\145\156\164\76", 
"\74\157\72\104\157\143\165\155\145\156\164\120\162\157\160\145\162\164\151\145\163\76", 
"\74\57\157\72\104\157\143\165\155\145\156\164\120\162\157\160\145\162\164\151\145\163\76", "\74\164\72\144\157\143\165\155\145\156\164\124\151\164\154\145\76", 
"\74\57\164\72\144\157\143\165\155\145\156\164\124\151\164\154\145\76", "\74\167\72\142\157\144\171\76", "\74\57\167\72\142\157\144\171\76", 
"\74\167\72\144\157\143\165\155\145\156\164\103\157\156\143\154\165\163\151\157\156\76", 
"\74\57\167\72\144\157\143\165\155\145\156\164\103\157\156\143\154\165\163\151\157\156\76", "\167\72\163\164\171\154\145", "\167\72\166\141\154", 
"\167\72\150\145\151\147\150\164", "\167\72\164\171\160\145", "\167\72\146\157\156\164", null, null, "\72", 
"\75", "\42", null, null, null, "\44", "\74", null, "\76", null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public CompisTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public CompisTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 44; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1fffffff01L, 
};
static final long[] jjtoSkip = {
   0xfeL, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[44];
    private final int[] jjstateSet = new int[2 * 44];

    
    protected char curChar;
}
