/* Generated By:JavaCC: Do not edit this line. CompisTreeConstants.java Version 6.0_1 */
public interface CompisTreeConstants
{
  public int JJTSTART = 0;
  public int JJTDOC_STRUCT = 1;
  public int JJTPROPERTIES = 2;
  public int JJTTITLE = 3;
  public int JJTBODY = 4;
  public int JJTCONCLUSION = 5;
  public int JJTEXPR_LIST = 6;
  public int JJTTAG_LIST = 7;
  public int JJTTAG_INT = 8;
  public int JJTTAG_STRING = 9;
  public int JJTCONTENT = 10;
  public int JJTFINALCONTENT = 11;


  public String[] jjtNodeName = {
    "START",
    "DOC_STRUCT",
    "PROPERTIES",
    "TITLE",
    "BODY",
    "CONCLUSION",
    "EXPR_LIST",
    "TAG_LIST",
    "TAG_INT",
    "TAG_STRING",
    "CONTENT",
    "FINALCONTENT",
  };
}
/* JavaCC - OriginalChecksum=3d76e8b34cf382944c7b7b1d83374fc3 (do not edit this line) */
